//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTJ.PowerApps.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstagramFile
    {
        public int Id { get; set; }
        public string Filename { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public byte[] Content { get; set; }
    }
}
